### ISSUE TITLE
Port case synthesizer (generator) to django

### ISSUE THREAD

**Issue by neopostmodern** [FG-AI4H-TG-Symptom/fgai4h-tg-symptom-assessment-mmvb-backend#46]

**Comment by maccinza** [comment]
For this one what are we considering as the goal?
  1. Having an api endpoint which is able to generate cases on the fly (and store them into the db);
  2. Easily generate and load synthetic cases onto the database with a command;
  3. Both of the above;

@neopostmodern @mzwiessele

**Comment by neopostmodern** [comment]
I'd say (1) is the priority, (2) only if the effort is negligible.
