### ISSUE TITLE
Restructure folders

### ISSUE THREAD

**Issue by neopostmodern** [FG-AI4H-TG-Symptom/fgai4h-tg-symptom-assessment-mmvb-backend#62]
now that all the big PRs are merged we should take a second to restructure the repo. my suggestions would be:

- delete `old_backend` – we have should a branch for that (we actually forgot to branch before the last merge, so we should retroactively branch)
- move everything inside `mmvb_backend` up one level and remove the folder

thoughts?

**Comment by maccinza** [comment]
I would not move `mmvb_backend` and remove the folder because it is not only a folder but a `django project`.

**Comment by mzwiessele** [comment]
Removing the folder will be enough, we have the release of the master: https://github.com/FG-AI4H-TG-Symptom/fgai4h-tg-symptom-assessment-mmvb-backend/releases/tag/MMVB2.0.5
